config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  
  root 'landing#index'
  get 'landing/index'
  resources :tweets
  resource :profile
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
end

app/models/tweet.rb
class Tweet < ApplicationRecord
    belongs_to :user
    validates :tweet, presence: true, length: { maximum: 140, message: 'You talk too much.'}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :tweets
  has_one :profile
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception


      before_action :configure_permitted_parameters, if: :devise_controller?

    protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up,        keys: [:username])
      devise_parameter_sanitizer.permit(:account_update, keys: [:username])
    end
  
  
  
  
  
  
  
  
  
  def after_sign_in_path_for(resource)
    tweets_path
  end
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  def index
    @user = current_user
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
    before_action :set_profile, only: [:show, :edit, :update, :destroy]
    def edit
        @profile = Profile.find_or_initialize_by(user: current_user)
    end

    def create
      @profile = Profile.new(profile_params)
      @profile.user = current_user
  
      respond_to do |format|
        if @profile.save
          format.html { redirect_to tweets_path, notice: 'Profile was successfully created.' }
          format.json { render :show, status: :created, location: @profile }
        else
          format.html { render :new }
          format.json { render json: @profile.errors, status: :unprocessable_entity }
        end
      end
    end

    def update
      respond_to do |format|
        if @profile.update(profile_params) 
          format.html { redirect_to tweets_path, notice: 'Profile was successfully updated.' }
          format.json { render :show, status: :ok, location: @profile }
        else
          format.html { render :edit }
          format.json { render json: @profile.errors, status: :unprocessable_entity }
        end
      end 
    end
    
    private
    def set_profile
      if params[:id]
        @profile = Profile.find_by(user_id: params[:id])
      else
        @profile = Profile.find_by(user: current_user)
      end
    end

    def profile_params
      params.require(:profile).permit(:nickname, :username, :bio)
    end
end

app/controllers/support_controller.rb
class SupportController < ApplicationController
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :authenticate_user!

  def index
    @tweets = Tweet.all.order('created_at DESC')
    @user = current_user
    # @profile = current_user.profile
  end

  def new
    @tweet = Tweet.new    
  end

  def create
    # render plain: params[:post].inspect
    # save
    @tweet = Tweet.new(post_params)
    @tweet.user = current_user

    respond_to do |format|
        if @tweet.save
        format.html { redirect_to tweets_path, notice: 'Tweeted.' }
        format.json { render :show, status: :created, location: @tweet }
        else
        format.html { redirect_to tweets_path, notice: 'Tweet error' }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
        end
    end
  end  

  def destroy
  end

  private
    def post_params
        params.require(:post).permit(:tweet)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/landing_helper.rb
module LandingHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/support_helper.rb
module SupportHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/landing/index.html.erb
<div class="jumbotron text-center">
    <h1>WELCOME TO OKITTER</h1><br>
    <%= link_to 'LOG IN', new_user_session_path, class: "btn btn-info" %>
    <%= link_to 'CREATE ACCOUNT', new_user_registration_path, class: "btn btn-primary" %>
    <%= link_to 'log out', destroy_user_session_path, class: 'btn btn-light', method: :delete %>

    <% if @user.present? %>
        <br><br>
        <span>Hello <%= link_to @user.username, tweets_path %>.</span>
    <% end %>
</div>

app/views/layouts/_footer.html.erb
<hr>
<footer class="footer text-center">
    <%= link_to '©Okitter', root_path, class: "text-muted" %>
</footer>

app/views/layouts/_header.html.erb
<header>
        <%# link_to "sample app", root_path, id: "logo" %>
          <ul class="nav justify-content-center">
              <li  class="nav-item"><%= link_to "something", '#', class: "nav-link active" %></li>
              <li  class="nav-item"><%= link_to "something", '#', class: "nav-link active" %></li> 
              <li  class="nav-item"><%= link_to "something", '#', class: "nav-link active" %></li>
          </ul>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Okitter</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="container">
    <%# render 'tweets/header' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </div>
  </body>
</html>

app/views/profiles/_form.html.erb
<%= form_with(model: profile, url: profile_url, local: true) do |form| %>
  <% if profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%# form.label :nickname %><br>
    <%# form.text_field :nickname, id: :profile_nickname %>
  </div>

  <div class="field">
    <%= form.label :bio %><br>
    <%= form.text_area :bio, id: :profile_bio %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<h1>Edit</h1>

<%= render 'form', profile: @profile %>

app/views/profiles/show.html.erb
<h2>My profile</h2>

app/views/tweets/destroy.html.erb
<h1>Tweets#destroy</h1>
<p>Find me in app/views/tweets/destroy.html.erb</p>

app/views/tweets/index.html.erb
    <span class="notice"><%= notice %></span>
    <span class="alert"><%= alert %></span>
    <span style="float:right;"><%= link_to 'Log out', destroy_user_session_path, method: :delete %></span>

<div class="jumbotron text-center">

	<h1>What's happening? </h1>

	<%= form_with scope: :post, url: tweets_path do |f| %>
		<%= f.text_field :tweet, style: "width: 600px; margin: 30px;" %>
		<p><%= f.submit "tweet", class: "btn btn-primary" %></p>
	<% end %>

</div>

	<div class="row">
		<div class="col-sm-3">
		<div class="card" style="width: 100%; padding: 12px;">
			<img class="card-img-top" src="http://i1.kym-cdn.com/photos/images/newsfeed/000/415/209/3b4.png" alt="Card image cap">
			<div class="card-block">
				<h4 class="card-title"><%= @user.try(:username) %></h4>
				<p class="card-text"> 
				<%= @user.profile.try(:bio) %>
				<p><%= link_to 'Edit profile', edit_profile_path %></p>
				</p>
			</div>
		</div>
			
		</div>
			<ul class="col-sm-6 list-group">
				<% @tweets.each do |t| %>
						<li class="list-group-item">
							<p><%= t.tweet %></p>
							<div class="tweet-footer">
								<span ><%= t.user.username %></span> | 
								<span><%= t.created_at.in_time_zone("Melbourne").strftime('%A %d %b %Y %H:%M') %></span>
							</div>
						</li>
				<% end %>
			</ul>
		<div class="col-sm-3"></div>

		
	</div>

app/views/tweets/new.html.erb
<h2>Add new post</h2>
<%= form_for :post, url: tweets_path do |f| %>
    
    <p>
    <%= f.text_field :tweet, placeholder: 'enter title' %>
    <% if @tweet.errors.messages[:tweet].any? %>
        <span class="error"><%= @tweet.errors.messages[:tweet][0] %></span>
    <% end %>
    </p>

    <p><%= f.submit %></p>
<% end %>